// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoBIHn4feQKVdztTmLlPr0H9vdqChkJss',
    appId: '1:832959215934:web:6f8baec0081d07d9f1146f',
    messagingSenderId: '832959215934',
    projectId: 'dashboard-notif',
    authDomain: 'dashboard-notif.firebaseapp.com',
    storageBucket: 'dashboard-notif.firebasestorage.app',
    measurementId: 'G-QYHVVZQVFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxLTWGU7PWyuXQaChm-bTqB_5uFrPYII',
    appId: '1:832959215934:android:21929a237ae73693f1146f',
    messagingSenderId: '832959215934',
    projectId: 'dashboard-notif',
    storageBucket: 'dashboard-notif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYu0V37xdQZiLwzr-u9f819pA6duUdtkY',
    appId: '1:832959215934:ios:930320f66faa1d49f1146f',
    messagingSenderId: '832959215934',
    projectId: 'dashboard-notif',
    storageBucket: 'dashboard-notif.firebasestorage.app',
    iosBundleId: 'com.bprsupra.dashboard',
  );
}
